version: '3'

services:
  postgres:
    image: postgres:15
    container_name: integration-tests-prisma
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=tests
    
    ports:
      - 5433:5432
    